name: Test pipeline
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9']
    name: Testing quilla with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install firefox
        run: sudo apt install firefox

      - name: Get geckodriver
        run: ./scripts/get_geckodriver.sh

      - name: Install wheel
        run: pip install wheel

      - name: Install all dependencies
        run: pip install -e .[all]

      - name: Run linter
        run: flake8

      - name: Run static type checker
        run: mypy

      - name: Run tests
        run: pytest --quilla-opts="--image-directory ./images"

      - name: Export docs as an artifact
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: image_artifacts
          path: ./images/runs
