name: Test pipeline
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9']
    name: Testing quilla with python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install all dependencies
        run: pip install -e .[all]

      - name: Install firefox
        run: sudo apt install firefox

      - name: Get chromedriver
        run: ./scripts/get_geckodriver.sh

      - name: Run linter
        run: flake8

      - name: Run static type checker
        run: mypy

      - name: Run tests
        run: pytest
